### ISSUE TITLE
[Code] When to release the source code?

### ISSUE THREAD

**Issue by Aopolin-Lv** [YanjieZe/GNFactor#1]
Hello, congratulations on your excellent work. I am very interested in this work and want to re-implement it. So if you release the source code, please let me know as soon as possible.

**Comment by YanjieZe** [comment]
Hi,

Thank you for interest!
I am cleaning the code, and I will possibly release it this week.

Yanjie Ze

**Comment by YanjieZe** [comment]
The code has been released, together with user-friendly guidance. 

Have a try!
