### ISSUE TITLE
Version of CoppeliaSim

### ISSUE THREAD

**Issue by bb0928** [YanjieZe/GNFactor#12]
Hi, i was using ubuntu 20.04 and have already installed the simulator before working on this project.
However, when i started to record demonstrate data, i encountered an error below.
`(gnfactor) user@user-System-Product-Name:~/GNFactor$ bash scripts/gen_demonstrations.sh open_drawer
[NeRFTaskRecorder] num_views: 50
  0%|                                                   | 0/200 [00:00<?, ?it/s]libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast

Error: signal 11:

/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_Z11_segHandleri+0x30)[0x7fbdb8210ae0]
/lib/x86_64-linux-gnu/libc.so.6(+0x43090)[0x7fbde2c0d090]
/lib/x86_64-linux-gnu/libc.so.6(+0x188915)[0x7fbde2d52915]
/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_Z15initGl_ifNeededv+0x11c)[0x7fbdb83b6cac]
/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_ZN19COffscreenGlContextC1EiiiP9QGLWidgetii+0x1d2)[0x7fbdb841aff2]
/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_ZN20CVisionSensorGlStuffC1EiiibP9QGLWidgetbbii+0x7d)[0x7fbdb841c83d]
/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_ZN13CVisionSensor45createGlContextAndFboAndTextureObjectIfNeededEb+0x19d)[0x7fbdb80e292d]
/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_ZN13CVisionSensor13detectEntity2Eibbbb+0x35f)[0x7fbdb80e746f]
/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_ZN13CVisionSensor44detectVisionSensorEntity_executedViaUiThreadEibbbb+0x79c)[0x7fbdb80e7f1c]
/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_ZN9CUiThread27__executeCommandViaUiThreadEP16SUIThreadCommandS1_+0x14a2)[0x7fbdb836f7c2]
QMutex: destroying locked mutex
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast

Error: signal 11:

/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_Z11_segHandleri+0x30)[0x7fa4d46a2ae0]
/lib/x86_64-linux-gnu/libc.so.6(+0x43090)[0x7fa4ff05f090]
/lib/x86_64-linux-gnu/libc.so.6(+0x188915)[0x7fa4ff1a4915]
/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_Z15initGl_ifNeededv+0x11c)[0x7fa4d4848cac]
/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_ZN19COffscreenGlContextC1EiiiP9QGLWidgetii+0x1d2)[0x7fa4d48acff2]
/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_ZN20CVisionSensorGlStuffC1EiiibP9QGLWidgetbbii+0x7d)[0x7fa4d48ae83d]
/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_ZN13CVisionSensor45createGlContextAndFboAndTextureObjectIfNeededEb+0x19d)[0x7fa4d457492d]
/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_ZN13CVisionSensor13detectEntity2Eibbbb+0x35f)[0x7fa4d457946f]
/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_ZN13CVisionSensor44detectVisionSensorEntity_executedViaUiThreadEibbbb+0x79c)[0x7fa4d4579f1c]
/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libcoppeliaSim.so.1(_ZN9CUiThread27__executeCommandViaUiThreadEP16SUIThreadCommandS1_+0x14a2)[0x7fa4d48017c2]
QMutex: destroying locked mutex
`
I am wondering if this is because the version is incorrect? my version is CoppeliaSim_Edu_V4_1_0_Ubuntu20_04. Same to yours except the version of ubuntu.
Could you please offer any help about this? Thanks!

**Comment by DingChunQ** [comment]
Same problem
Have you solved it?

**Comment by bb0928** [comment]
yeah, just add export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libffi.so.7 to bashrc or simply add it in terminal before running training command.

> Same problem Have you solved it?

**Comment by bb0928** [comment]
> Same problem Have you solved it?

你好，如果你也在复现这篇论文的话方便加个联系方式一起讨论吗？vx:Bob20020928
