### ISSUE TITLE
Code indentation error

### ISSUE THREAD

**Issue by SanMumumu** [YanjieZe/GNFactor#4]
Hi,

Is there a code indentation error here?

https://github.com/YanjieZe/GNFactor/blob/bc9cbdda6dcdd88fd762baf6749752b42e03577a/GNFactor/agents/gnfactor_bc/neural_rendering.py#L327-L345

**Comment by YanjieZe** [comment]
Hi, it seems no error here. could it run properly on your computer?
If there are indentation errors on your computer, maybe you could adjust directly. I think it might be possibly caused by the code editor or something.

**Comment by SanMumumu** [comment]
Yeah, it works.
