### ISSUE TITLE
Loss_balance

### ISSUE THREAD

**Issue by SanMumumu** [YanjieZe/GNFactor#5]
Hi,

I noticed that in this code you set the weights to 1 and 0.01. Does this mean that the rendering loss plays a very small role?
https://github.com/YanjieZe/GNFactor/blob/bc9cbdda6dcdd88fd762baf6749752b42e03577a/GNFactor/agents/gnfactor_bc/qattention_gnfactor_bc_agent.py#L868

In fact, in my task, the total_loss is about 20, while the rendering_loss is very small, such as 1.12. 

They themselves differed by an order of magnitude. If multiplied by 0.01, it would be a difference of three orders of magnitude. Is that so? 

Alternatively, can you tell me what the optimal ratio is? This saves me some trial and error time. Thanks very much.

**Comment by YanjieZe** [comment]
Hi,

We tried 1, 0.1, 0.01 in previous experiments and find that 0.01 is slightly better, but not significantly. Therefore the "optimal ratio" from these experiments is 0.01.

If you have enough computation, it is encouraged to try more weights beside these.

**Comment by SanMumumu** [comment]
OK, thank you very much for your reply！

**Comment by SanMumumu** [comment]
Hi, 

Sorry to bother you again. I want to know how you determine the direction vector  `_coord_trans` ? I can't reproduce image that reconstructed based on stable diffusion&RGB under the new robot benchmark. 

https://github.com/YanjieZe/GNFactor/blob/bc9cbdda6dcdd88fd762baf6749752b42e03577a/GNFactor/agents/gnfactor_bc/qattention_gnfactor_bc_agent.py#L126

https://github.com/YanjieZe/GNFactor/blob/bc9cbdda6dcdd88fd762baf6749752b42e03577a/GNFactor/agents/gnfactor_bc/qattention_gnfactor_bc_agent.py#L224

**Comment by YanjieZe** [comment]
Hi, this transformation is to align the coordinate system. I think in our implementation, cameras/algorithms follow the opengl/opencv tradition, and then we need to align them. In your case, make sure the coordinate systems are aligned. You could try to remove this transformation to see if it works better.

**Comment by SanMumumu** [comment]
Thank you so much! I'll try it. o(*￣▽￣*)ブ
