### ISSUE TITLE
Visualization error

### ISSUE THREAD

**Issue by xiaohao9999** [YanjieZe/GNFactor#6]
Hello, I used your code, but in the image display, I found that it did not achieve the effect presented in your paper. Instead, I had terrible results.

Can you tell me where the problem is?

The picture below is the result after training for 70k steps
![image](https://github.com/YanjieZe/GNFactor/assets/146507142/5daf73f9-39a5-4503-9319-407749156343)

**Comment by YanjieZe** [comment]
Hi, I was wondering whether this is caused by this transformation, mentioned by another user: [here](https://github.com/YanjieZe/GNFactor/issues/5#issuecomment-2081371449). Could you try to set it to all 1 to see?

Basically, make sure that the camera poses are right for the nerf rendering.

**Comment by xiaohao9999** [comment]
Hello author, after I modified the first point you mentioned and checked the camera parameters for nerf rendering.

But I still get the wrong rendering result below

![image](https://github.com/YanjieZe/GNFactor/assets/146507142/817d92b4-0077-4019-aa4a-30d1bd9bb6e2)

Could you please tell me what else I should check?

**Comment by YanjieZe** [comment]
Hi, how many camera views do you use?

**Comment by YanjieZe** [comment]
And could you try to set BC loss to be 0, and check whether only rendering loss could work?

**Comment by xiaohao9999** [comment]
Well，I have set the BCE loss to 0.0001. And I only used one camera. At first, I thought it was a coordinate system mapping issue, but I carefully checked the code to ensure the coordinate systems are consistent, yet the problem still occurs.

**Comment by xiaohao9999** [comment]
By the way I also want to ask why the camera's focus to be negative. For example,-175. My is  75. But I thconvergingink it doesn't matter. And it seems that my rendering loss does not converging

**Comment by xiaohao9999** [comment]
Hi,

When I set `_coord_trans ` all to 1, I can render some in one scene, but the rendering results in other scenes are still very poor. Can you tell me what else I need to check?

![image](https://github.com/YanjieZe/GNFactor/assets/146507142/af2dffa3-e6c7-4f88-881c-681b16fb164e)
